version: 2
jobs:
  one:
<<<<<<< HEAD
    docker:
=======
    docker
>>>>>>> e1a5eefe3b0a234c9da67b7b374cda39516797a1

    steps:
      - checkout
      - run: docker build -t karim6b/docker-react -f Dockerfile.dev .

  two:
    docker

    steps:
      - checkout
      - run: docker run -e CI=true karim6b/docker-react npm run test

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two