version: 2
jobs:
  one:
    docker

    steps:
      - checkout
      - run: docker build -t karim6b/docker-react -f Dockerfile.dev .

  two:
    docker

    steps:
      - checkout
      - run: docker run -e CI=true karim6b/docker-react npm run test

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two